### ISSUE TITLE
Index out of bounds error when calling `ctx.assert`

### ISSUE THREAD

**Issue by rachitnigam** [elliottt/easy-smt#10]
I'm using the library to generate and discharge some assertions but it seems to throw a bounds-check error in an `unsafe` code block. Not sure how I should debug it since it seems related to the arena-based interning.

### Reproduction

```
git clone https://github.com/cucapra/filament.git
cd filament
git fetch --all
git checkout f53494b
cargo run -- primitives/state.fil --show-ir
```

The program errors out with:
```
thread 'main' panicked at 'index out of bounds: the len is 77 but the index is 87'
```

**Comment by elliottt** [comment]
I'll take a look tonight, thanks for the report!

**Comment by rachitnigam** [comment]
Figured out the problem! I was mistakenly using two different `Context` objects which was causing the problem!

**Comment by elliottt** [comment]
Ah, that would do it!
