### ISSUE TITLE
Ability to write solver interactions to a (replayable) file

### ISSUE THREAD

**Issue by avanhatt** [elliottt/easy-smt#3]
Would it be possible to also have a mode that echos all solver interactions to a file that can be replayed by directly feeding to a solver? We have some cases where for debugging/performance investigations (and for sending SMT-LIB files to other folks), it's convenient to interact with just a single file.

Basically, I'm thinking of what was adding in the logging commit (https://github.com/elliottt/easy-smt/commit/963ee2d1b815b7246f4c9c17edbdea36226292f6) but without the logging metadata/arrows. We could strip this information ourselves but it seems like this might be nice as a more general optional feature.

Thanks, we're excited to use this crate!

To clarify: we don't particularly need what is returned from the solver for this use case, just want is sent to the solver's standard in.

**Comment by fitzgen** [comment]
Yeah this is definitely possible.

Are you imagining providing a file to write to when constructing the `easy_smt::Context`?

**Comment by avanhatt** [comment]
No real preference between providing a file vs a path/filename for a new file to be created. And yes, I was thinking on a per-`easy_smt::Context` level.
