### ISSUE TITLE
Support for sending custom expressions to the solver

### ISSUE THREAD

**Issue by UnsignedByte** [elliottt/easy-smt#30]
Hi,

`easy_smt` currently provides nice access to creating custom `atom`s and using them in custom expressions, but has no way to actually send these to the solver for the user (as `solver.send` is private). This is useful for example with [optimization in z3](https://microsoft.github.io/z3guide/docs/optimization/arithmeticaloptimization/) which provides special `(minimize expr)` and `(maximize expr)` expressions that need to be sent to the solver.

Such expressions can be made using the following
```rust
let minimize = self.sol.atom("minimize");
let expr = self.sol.list(vec![minimize, self.minimize_expr.clone()]);

self.sol.send(expr); // missing
```
but they cannot yet be sent to the solver. This should be a relatively simple patch to include a wrapper for `solver.send`.

**Comment by fitzgen** [comment]
This is definitely something we should support. Would you be open to whipping up a PR?
