### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by fitzgen** [elliottt/easy-smt#6]
Anything we want to have before publishing to crates.io?

**Comment by elliottt** [comment]
Have we finished binding all the theories defined in smtlib-2? It might also be good to just release it and see what people report as the shortcomings of the library...

**Comment by fitzgen** [comment]
> Have we finished binding all the theories defined in smtlib-2?

Not totally sure, I've been meaning to go through the spec and ensure coverage. No harm in publishing sooner rather than later though. Not guaranteeing feature completeness or 1.0 stability yet.

**Comment by elliottt** [comment]
I say we publish it then!
